IMAGE_NAME = "geerlingguy/ubuntu1804"
N = 2
CIDR_PREFIX = "10.118.19"  # because k=11 and s=19, therefore k8s=118.19 :)

Vagrant.configure("2") do |config|
  vagrant_root = File.dirname(__FILE__)
  ENV['ANSIBLE_ROLES_PATH'] = "#{vagrant_root}/roles"

  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.define "k8s-master" do |master|
    master.vm.box = IMAGE_NAME
    master.vm.network "private_network", ip: CIDR_PREFIX+".10"
    master.vm.hostname = "k8s-master"
    master.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.extra_vars = {
        # k8s_base is an implicit dependency
        k8s_base_node_ip: CIDR_PREFIX+".10",
        k8s_base_ver: "1.16.2-00",
        # k8s_init is an implicit dependency
        k8s_init_cidr: "192.168.0.0/16",
        k8s_init_node_ip: CIDR_PREFIX+".10",
        k8s_init_node_name: "{{ inventory_hostname }}",
        # this role configuration
        k8s_calico_ver: "v3.10"
      }
      ansible.galaxy_role_file = 'roles/requirements.yml'
      ansible.galaxy_roles_path = 'roles'
      #ansible.verbose = "-vvv"
    end
  end

#  (1..N).each do |i|
#    config.vm.define "k8s-node-#{i}" do |node|
#      node.vm.box = IMAGE_NAME
#      node.vm.network "private_network", ip: CIDR_PREFIX+"#{10+i}"
#      node.vm.hostname = "k8s-node-#{i}"
#      node.vm.provision "ansible" do |ansible|
#        ansible.playbook = "node.yml"
#        ansible.extra_vars = {
#          k8s_node_ip: CIDR_PREFIX+"#{10+i}",
#        }
#        ansible.galaxy_role_file = 'roles/requirements.yml'
#        ansible.galaxy_roles_path = 'roles'
#      end
#    end
#  end
end
